version: '3.1'

services:
  db-postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: myUser
      POSTGRES_PASSWORD: myPassword
      POSTGRES_DB: u_service
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - posgres-network
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
volumes:
  postgres-data:
    driver: local
    name: postgres-data
networks:
  posgres-network:
    name: posgres-network